# Generated by Django 3.0.8 on 2020-08-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200801_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modtimestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
