# Generated by Django 3.0.8 on 2020-08-08 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200806_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='modtimestamp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
